#!/bin/bash
# Generates <grapheme>.wav (e.g. c.wav, sh.wav) under FlashCards/Resources/Sounds/Segmentation.
# Uses macOS `say` + `afconvert` — same format as Scripts/generate_word_wavs.py (LEI16@22050).
# `s.wav` is generated by `generate_s_fricative_wav.py` (TTS cannot produce a clean voiceless /s/).
# Default voice: Kate (en_GB female). Override: VOICE=Samantha ./generate_segmentation_sounds.sh
#
# Each clip is **one syllable** (quick phonics-style sound), not a stretched or repeated letter.
# Example: “cat” → c.wav ≈ one beat “cuh” (/k/ + schwa), not “kuh-kuh-kuh”.
# Whole-word audio stays in WordsAudio; these are only per-segment taps.
#
# One file per grapheme still can’t match every word context; see bottom for IPA/SSML options.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/FlashCards/Resources/Sounds/Segmentation"
VOICE="${VOICE:-Kate}"
# Slightly fast = shorter clips; still clear. Override: SAY_RATE=200 ./generate_segmentation_sounds.sh
SAY_RATE="${SAY_RATE:-220}"
TMP="$(mktemp /tmp/segXXXX.aiff)"

mkdir -p "$OUT"

rm -f "$OUT"/seg_*.wav 2>/dev/null || true

# Single-syllable prompts (phonics-style; voice-dependent).
phrase_for() {
  case "$1" in
    c) echo "cuh" ;;
    t) echo "tuh" ;;
    d) echo "duh" ;;
    g) echo "guh" ;;
    h) echo "huh" ;;
    p) echo "puh" ;;
    r) echo "ruh" ;;
    n) echo "nuh" ;;
    sh) echo "shh" ;;
    a) echo "ah" ;;    # one syllable; short vowel approx (as in cat)
    e) echo "eh" ;;
    i) echo "ih" ;;
    o) echo "oh" ;;
    u) echo "uh" ;;
    ai) echo "ay" ;;   # one syllable, rain-style
    *) echo "$1" ;;
  esac
}

# Unique graphemes from phonics_modules_poc.json segmentation (CVC + ship, rain, …).
for g in c a t d o g s u n h p e sh ai r i; do
  if [[ "$g" == "s" ]]; then
    python3 "$ROOT/Scripts/generate_s_fricative_wav.py" -o "$OUT/s.wav"
    echo "Wrote s.wav (synthetic /s/ fricative via generate_s_fricative_wav.py)"
    continue
  fi
  phrase="$(phrase_for "$g")"
  say -v "$VOICE" -r "$SAY_RATE" -o "$TMP" "$phrase"
  afconvert -f WAVE -d LEI16@22050 "$TMP" "$OUT/${g}.wav" 1>/dev/null
  echo "Wrote ${g}.wav ($phrase) voice=$VOICE rate=$SAY_RATE"
done

rm -f "$TMP"
echo "Done: $OUT"

# --- If `say` is not good enough ---
# • Amazon Polly / Google Cloud TTS / Azure Speech: SSML <phoneme alphabet="ipa" ph="..."/> for exact phones.
# • eSpeak-NG: `espeak-ng -v en-gb -w out.wav "[æ]"` (IPA in brackets; quality is robotic but consistent).
# • Audacity (or Logic/GarageBand): record your voice or Polly export, trim silence, normalize, export WAV.
# • Praat: synthesize or edit phoneme tiers if you want research-grade control.
# • Forvo / dictionary clips: check licensing before shipping in an app.
